# Generated by Django 2.0.2 on 2018-08-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='details',
            field=models.TextField(default=None, null=True),
        ),
    ]
